"""more user data

Revision ID: 07881738452b
Revises: 64782bf7480d
Create Date: 2021-05-07 14:30:00.609450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07881738452b'
down_revision = '64782bf7480d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('role', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
